# Generated by Django 4.1.4 on 2023-01-13 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 17, 26, 49, 588508), unique=True),
        ),
    ]
