# Generated by Django 4.1.4 on 2023-01-23 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_davomat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 18, 40, 52, 482377), unique=True),
        ),
    ]
