# Generated by Django 4.1.4 on 2023-02-13 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_davomat_date_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 22, 20, 21, 559602)),
        ),
    ]
