# Generated by Django 4.1.4 on 2023-02-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='type',
            field=models.CharField(blank=True, choices=[('naqd', 'Naqd'), ('plastik karta', 'Plastik karta'), ('click', 'Click'), ("pul ko'chirish", "Pul ko'chirish"), ('boshqa', 'Boshqa')], max_length=55, null=True),
        ),
    ]
