# Generated by Django 4.1.4 on 2023-02-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_groups_day'),
        ('payment', '0002_studentpayment_description_alter_studentpayment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.groups'),
        ),
    ]
