# Generated by Django 4.1.4 on 2023-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_studentpayment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='type',
            field=models.CharField(blank=True, choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ("o'tkazma", "O'tkazma")], max_length=55, null=True),
        ),
    ]
