# Generated by Django 4.1.4 on 2023-02-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_studentpayment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='type',
            field=models.CharField(blank=True, choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ("ko'chirma", "Ko'chirma")], max_length=55, null=True),
        ),
    ]
