# Generated by Django 4.1.4 on 2023-01-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0002_alter_groups_course_alter_groups_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='student',
        ),
        migrations.AddField(
            model_name='groups',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
    ]
