# Generated by Django 4.1.4 on 2023-01-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0003_remove_groups_student_groups_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='student',
        ),
        migrations.AddField(
            model_name='groups',
            name='student',
            field=models.ManyToManyField(to='students.student'),
        ),
    ]
