# Generated by Django 4.1.4 on 2023-01-13 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_remove_groups_course_remove_groups_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
