# Generated by Django 4.1.4 on 2023-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_groups_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='day',
            field=models.CharField(blank=True, choices=[('juft', 'Juft kunlar'), ('toq', 'Toq kunlar')], max_length=10, null=True),
        ),
    ]
