# Generated by Django 4.1.4 on 2023-01-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_groups_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='course',
            field=models.ManyToManyField(related_name='course', to='courses.course'),
        ),
    ]
