# Generated by Django 4.1.4 on 2023-01-23 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_davomat_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_alter_groups_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': ' Class Room ', 'verbose_name_plural': ' Class Room '},
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ManyToManyField(related_name='classrooms', to='courses.course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='day',
            field=models.CharField(blank=True, choices=[('juft', 'Juft kunlar'), ('toq', 'Toq kunlar')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='education',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room',
            field=models.ManyToManyField(related_name='classrooms', to='courses.room'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('waiting', 'Waiting')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(to='students.student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='Class Room',
        ),
    ]
