# Generated by Django 4.1.4 on 2023-02-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_classroom_options_classroom_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='day',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='education',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='room',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='start',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='status',
        ),
    ]
