# Generated by Django 4.1.4 on 2023-02-06 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_remove_classroom_course_remove_classroom_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='center.teacher'),
        ),
        migrations.RemoveField(
            model_name='groups',
            name='course',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='room',
        ),
        migrations.AlterField(
            model_name='groups',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groups',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.course'),
        ),
        migrations.AddField(
            model_name='groups',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.room'),
        ),
    ]
