# Generated by Django 4.1.4 on 2023-02-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_groups_teacher_remove_groups_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='finish_lesson',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='start_lesson',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
