# Generated by Django 4.1.4 on 2023-02-19 05:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_classroom_student_alter_groups_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=100, null=True),
        ),
    ]
